In [1]:
import scipy as spy
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy import stats
from scipy import misc
from scipy.stats import norm

%matplotlib inline

In [2]:
norm.cdf(0)

0.5

In [3]:
norm.cdf([-1., 0, 1])

array([0.15865525, 0.5       , 0.84134475])

In [4]:
x_test = np.array([-1., 0, 1])
norm.cdf(np.array(x_test))

array([0.15865525, 0.5       , 0.84134475])

In [5]:
norm.mean(), norm.std(), norm.var()

(0.0, 1.0, 1.0)

In [6]:
norm.stats(moments="mv")

(array(0.), array(1.))

In [7]:
norm.ppf(0.5)

0.0

In [8]:
norm.rvs(size=7)

array([-0.45111439,  0.21313162, -1.41009788, -0.56197512,  0.39673972,
        1.7108506 ,  1.38164372])

In [9]:
np.random.seed(1234)

In [10]:
115/200

0.575

In [11]:
30/200

0.15

In [13]:
(85/200) + (30/200)

0.575

In [14]:
lampada = norm.rvs(size=1000)

array([ 4.71435164e-01, -1.19097569e+00,  1.43270697e+00, -3.12651896e-01,
       -7.20588733e-01,  8.87162940e-01,  8.59588414e-01, -6.36523504e-01,
        1.56963721e-02, -2.24268495e+00,  1.15003572e+00,  9.91946022e-01,
        9.53324128e-01, -2.02125482e+00, -3.34077366e-01,  2.11836468e-03,
        4.05453412e-01,  2.89091941e-01,  1.32115819e+00, -1.54690555e+00,
       -2.02646325e-01, -6.55969344e-01,  1.93421376e-01,  5.53438911e-01,
        1.31815155e+00, -4.69305285e-01,  6.75554085e-01, -1.81702723e+00,
       -1.83108540e-01,  1.05896919e+00, -3.97840228e-01,  3.37437654e-01,
        1.04757857e+00,  1.04593826e+00,  8.63717292e-01, -1.22091575e-01,
        1.24712954e-01, -3.22794806e-01,  8.41674713e-01,  2.39096052e+00,
        7.61995878e-02, -5.66445930e-01,  3.61419367e-02, -2.07497760e+00,
        2.47792200e-01, -8.97156784e-01, -1.36794833e-01,  1.82891913e-02,
        7.55413982e-01,  2.15268581e-01,  8.41008795e-01, -1.44581008e+00,
       -1.40197328e+00, -