In [1]:
import scipy as spy
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy import stats
from scipy import misc
from scipy.stats import norm

%matplotlib inline

In [2]:
norm.cdf(0)

0.5

In [3]:
norm.cdf([-1., 0, 1])

array([0.15865525, 0.5       , 0.84134475])

In [4]:
x_test = np.array([-1., 0, 1])
norm.cdf(np.array(x_test))

array([0.15865525, 0.5       , 0.84134475])

In [5]:
norm.mean(), norm.std(), norm.var()

(0.0, 1.0, 1.0)

In [6]:
norm.stats(moments="mv")

(array(0.), array(1.))

In [7]:
norm.ppf(0.5)

0.0

In [8]:
norm.rvs(size=7)

array([ 1.43732455,  0.03542418, -0.3676806 , -0.56137994, -1.6576221 ,
        0.89567894,  0.33263949])

In [9]:
np.random.seed(1234)

In [10]:
115/200

0.575

In [11]:
30/200

0.15

In [12]:
(85/200) + (30/200)

0.575

In [15]:
lampada = norm.rvs(size=100)